### ISSUE TITLE
Falta de Labels

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#1]
GitHub trae por defecto un conjunto de labels referencia bastante escaso por lo que es necesario añadamos suficientes para poder cubrir un mayor número de situaciones.

Serán necesarias labels de prioridad, estado, tipo y grupo para el desempeño del proyecto.

Hago referencia al repositorio demo como referencia ha esta necesidad:
[https://github.com/ArturoRonda/RecuentoAgoraUS/labels](url)

**Comment by jimdrix93** [comment]
Todas las labels están replicadas del repositorio demo.

Cierro la issue.
