### ISSUE TITLE
Situación actual para presentacion M2

### ISSUE THREAD

**Issue by jimdrix93** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#14]
Necesito saber que estará implementado para mañana a las 10.30, que tenemos la presentación del Milestone 2.

@Roldans tiene que decirme que tipos de recuentos de votos están implementados y cuales no.
@Javrd tiene que decirme si tiene implementada la Api Rest.
@ernestodtv tiene que decirme si el modelo de datos es para el Milestone 2 y si está hecho o no.

**Comment by Roldans** [comment]
Frente a los tipos de recuento implementados, ahora mismo está implementado el recuento de votación de aprobar multiple y unica (elige varios y elige uno)

Sobre el tema de la Api Rest, no se ha terminado de implementar

Por ultimo, el modelo de datos está terminado, aunque se está a espera una petición que se hizo a integración para modificar el modelo del sistema completo para poder implementar nuevos tipos de recuentos, por lo puede ser que deba ser modificado en futuros milestones
