### ISSUE TITLE
Dockerizar el proyecto y prepararlo para entrega a integración

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#15]
Para este Milestone 3 será necesario realizar una entrega al equipo de integración con el proyecto dockerizado tal como define el documento colgado en su repositorio:
[https://github.com/Proyecto-EGC-G1/Integracion-EGC-G1/blob/master/Documentaci%C3%B3n/Sistema_Votaciones/procedimiento_entrega_votaciones_1.0.pdf](url)
El lunes 18 es la fecha establecida para la primera prueba de integración.

**Comment by Javrd** [comment]
Ya se han agregado los ficheros necesarios para dockerizar el proyeto, pero es necesario también subirla a docker hub para que pueda descargarse pasandole al equipo de integración el nombre elegido para la imagen. Para subir la imagen, ¿es necesario crear una cuenta o lo hacemos con nuestra cuenta personal?

**Comment by ArturoRonda** [comment]
Desde integración han dicho que se podrá usar cualquier cuenta a decisión del subsistema.

**Comment by Javrd** [comment]
De acuerdo, ya he subido una primera versión de la imagen a docker hub y se irá actualizando conforme avancemos en el proyecto. Se puede obtener con:
```
docker pull javrd/recvotos
```
