### ISSUE TITLE
Versionado del proyecto

### ISSUE THREAD

**Issue by Javrd** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#18]
No se esta llevando a cabo un correcto versionado del proyecto. Propongo saquemos al menos una versión por milestone, llevando el estado en ese momento del proyecto testeado y desplegable a la rama master y se le etiquete con un número de versión, x.y.z, según los cambios que ha sufrido de una a otra versión el proyecto.

**Comment by ArturoRonda** [comment]
Se está trabajando en decidir cuál serán las versiones subidas a la rama master.
