### ISSUE TITLE
Milestones del proyecto

### ISSUE THREAD

**Issue by Javrd** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#19]
No se esta llevando a cabo un seguimiento de los milestones asociados a las issues. Propongo configurar los milestones programados desde la asignatura en el proyecto para asignar las issues a uno u otro milestone.

**Comment by ArturoRonda** [comment]
Debido a la altura del proyecto en la que nos encontramos será pospuesto a futuras versiones
