### ISSUE TITLE
Mapear información de bd de integración a nuestros modelos

### ISSUE THREAD

**Issue by Javrd** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#20]
Una vez que este configurada la base de datos de integración (#16), será necesario hacer consultas SQL desde python para obtener la información necesaria para un recuento representada con nuestro modelo de dominio de Django. 

Es necesaria la creación de un método que, llamandolo con la id de una votación, obtengan toda la información de la base de datos y pueble nuestro modelo.

**Comment by jimdrix93** [comment]
@Roldans me ha pedido ayuda porque esta teniendo problemas con la implementación del script.
