### ISSUE TITLE
Crear proceso de integración continua

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#21]
Para el proyecto es necesario implementar un sistema de integración continua de manera que podamos supervisar la estabilidad de las versiones de una forma ordenada y constante.

Una posible solución es utilizar travis como se ha visto en las prácticas de la asignatura, pero es posible si se aprueba en grupo emplear un sistema diferente.

**Comment by jimdrix93** [comment]
Me la asigno yo ya que no tengo ninguna issue asignada.

Utilizare travis para una versión de prueba e investigaré otros como jenkins, docker o maven.

**Comment by jimdrix93** [comment]
He subido el archivo ".travis.yml" para la configuración de la integración continua, pero necesito que @ArturoRonda active el repositorio en Travis para poder construir el proceso.

**Comment by jimdrix93** [comment]
El proceso de integración continua lo he tenido que probar en un Fork que he tenido que hacer al repositorio, ya que desde Travis no tenia permisos para verlo. 

El archivo de configuración no da fallos ni errores, solo quedaría que @ArturoRonda lo arranque desde Travis y si hay algunos tests más me los comuniquéis y los añado al archivo ".travis.yml".

**Comment by jimdrix93** [comment]
No hace falta arrancarlo, solo necesita revisión. 

Está funcionando en el repositorio.

**Comment by jimdrix93** [comment]
Cierro la issue ya que no se va añadir ninguna comprobación más al proceso de integración continua.
