### ISSUE TITLE
Diario del proyecto M4

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#25]
Entre lo entregables del proyecto para el M4 será necesario elaborar un documento en el cual figuren todas las reuniones realizadas como grupo y con el resto de grupos.

Sera conveniente adjuntar las actas de dichas reuniones.

**Comment by Alvachbur** [comment]
La tarea pasa a estado completada, a falta de que se deba realizar algún cambio o se realice alguna observación que requiera la re apertura de la misma
