### ISSUE TITLE
Primer commit con el proyecto base

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#3]
Es necesario commitear el proyecto base limpio sin ningún tipo de adición para poder llevar a cabo un buen seguimiento de su evolución, así como tener disponible un punto de retorno base claramente definido.

**Comment by Javrd** [comment]
Como es una tarea crítica y según lo que hemos hablado @ernestodtv y yo, voy a encargarme de realizar esta tarea.
