### ISSUE TITLE
Solicitud de cambio en el formato Json

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#31]
El equipo de Visualización de resultados ha solicitado una modificación en el
formato Json que empleamos para entregarles el resultado del recuento de la 
votación.

El cambio solicitado consisten en eliminar el campo quantity de result y dar el 
valor del recuento directamente en el campo result.

**Comment by ernestodtv** [comment]
Me pongo a investigar
