### ISSUE TITLE
Cambio en la documentación de la Wiki

### ISSUE THREAD

**Issue by jimdrix93** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#32]
Hay que actualizar en nuestro espacio de la wiki de egc (https://1984.lsi.us.es/wiki-egc/index.php/Recuento_de_votos_-_17_18_-_G1) el formato del json, ya que se ha cambiado. 

Deja de ser: "result": { "quantity": x } por { "result" : x }

**Comment by Alvachbur** [comment]
Se ha realizado la tarea asignada, y esta disponible para su observación por parte de otros grupos.
Closses #32
