### ISSUE TITLE
Creación de una Api RestFull

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#5]
Como ha definido el equipo de integración, para poder interactuar entre módulos se desarrollarán API's,
estas recibirán información en la llamada y devolverá el resultado mediante un Json.

En nuestro caso recibimos como parámetro de entrada una Poll id y deberemos devolver el resultado de la votación, además cómo funciona una vez implementada y como se ha implementado se recogerá en un documento junto al proyecto.

**Comment by Javrd** [comment]
Se va a crear la api de salida para visualización. Para las clases que manejan la api de almacenamiento se ha creado #12
