### ISSUE TITLE
Documentación de tipos de recuento

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#6]
Como módulo de recuento de votos debemos realizar una investigación sobre los distintos tipos de recuento que se podrían llevar a cabo para las votaciones, por lo tanto es necesario tener un documento junto a nuestro proyecto revisable por el resto de módulos para la toma de decisiones en cuanto a los posibles cambios.

**Comment by Roldans** [comment]
Se ha realizado incluyendo como tipos:
Recuento Borda
Recuento Borda Nauru
Recuento Borda personalizado
Votación de aprobación
Votación de aprobación única
