### ISSUE TITLE
Recuento Borda Simple

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#7]
No tenemos aún ningún sistema de recuento implementado, por lo que debemos tener al menos un recuento sencillo implementado para el dia de la presentación de incremento del dia 14/12/2017.

**Comment by Roldans** [comment]
Como el Documento "Tipos de Votaciones.pdf" define, el sistema de recuento Borda, da unos valores a las opciones de pregunta en función del orden en que el votante a colocado las opciones.
El problema es que este valor de la posición no se define en el modelo de dominio de nuestro sistema por lo que este sistema de recuento ni ninguno que tenga en cuenta la posición de las posiciones de las opciones de pregunta.

Como comenté en la ultima reunión, creo conveniente añadir un atributo Integer a la clase "OptionPerVote" con los cuales se podrían implementar todos los tipos de recuento definidos, ya sea dando:

'1' o '0' si no se tiene en cuenta el orden de los resultados
desde '1' hasta 'N' (siendo N el numero de posiciones posibles), para aquellos que tengan en cuenta las posiciones.

**Comment by ArturoRonda** [comment]
El campo ha sido aceptado por lo que puede procederse ha implementar este sistema de recuento.

**Comment by Roldans** [comment]
Hasta que no se implemente el cambio en la base de datos no se puede implementar este tipo de recuento.

Cierro la issue por limpieza, dejando pendiente implementar el recuento cuando se haga efectivo ese cambio

**Comment by ArturoRonda** [comment]
Integración de ultima hora ha decidido no realizar el cambio en la BD ya que la mayoría de los involucrados no responden, por tanto nos ha solicitado que se implemente pero quede comentado el código y listo para su uso en cuanto se realizara el cambio.
