### ISSUE TITLE
Documentación Instalación

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#8]
Antes del dia 14/12/2017 se debe llevar a cabo una documentación completa con la descripción de nuestro entorno de trabajo, junto a los procedimientos de instalación detallados en caso de que este fuera a ser reproducido por alguien hasta el momento ajeno al proyecto de recuento de votos.

**Comment by Javrd** [comment]
He realizado un primer acercamiento de la documentación de la instalación sobre readme.md en c802413bd562e9f45a3454c2dfe0f7fd8ea9cc4b pero debe completarse.
