### ISSUE TITLE
Recuento de votos ponderados por preferencia

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/RecuentoVotos-EGC-G1#9]
Como incremento para el M.2 se implementará un sistema de recuento de votos, apto para aquellos
con múltiples respuestas.

Posibles implementaciones:
-Valorar la primera respuesta con un valor igual al número de respuestas posibles y la última con 1.
-Que el usuario coloque en cada respuesta un valor indicando si preferencia.

**Comment by Roldans** [comment]
Este tipo de Recuento es equivalente al Borda Simple que ya ha sido pedido en otra issue
